name: PYMpublicidad
favicon: null
layout_spectrum: 0.5386568871326745
typography_spectrum: 0.898698367876932
title: 'P&M Publicidad SAS Â· Agencia Creativa'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6532749643083662
  lightness: 0.7871313199866563
  saturation: 0.03687039064243436
  rhythmicContrast: 0.8967415450606495
purpose: []
